### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by vwmaus** [vwmaus/model-reproducibility#19]
@pergerch @ptrkrnstnr, Is it possible to add support for Travis CI using the development interface? It should create a file called `.travis.yml` in the main folder.

**Comment by ptrkrnstnr** [comment]
Hello! 

 

As much as I found out, it is possible to add the support. I already connected my github account with travis ci. Unfortunately i cannot share my repositories with travis ci because I need to have an active subscription… This subscription costs 70$/month..

 

 



The next problem is that I cannot change my repository to private as it was forked by me: 



The only way i can do is to duplicate the repo, but then i’m the only contributor and cannot share the code with you…

 

Do you have any ideas fort hat problem?

 

Thanks!

 

Best, Peter

 

 

 

 

Von: Victor Maus [mailto:notifications@github.com] 
Gesendet: Donnerstag, 9. November 2017 10:21
An: vwmaus/model-reproducibility <model-reproducibility@noreply.github.com>
Cc: ptrkrnstnr <peter.kronsteiner@gmx.net>; Mention <mention@noreply.github.com>
Betreff: [vwmaus/model-reproducibility] Travis CI (#19)

 

@pergerch <https://github.com/pergerch>  @ptrkrnstnr <https://github.com/ptrkrnstnr> , Is it possible to add support for Travis CI using the development interface? It should create a file called .travis.yml in the main folder.

**Comment by vwmaus** [comment]
Travis CI should work for public repositories for free. @ptrkrnstnr let's take a look at it together this afternoon.

**Comment by ptrkrnstnr** [comment]
@vwmaus finally got the travis-ci script working!

**Comment by vwmaus** [comment]
Super, thanks!

**Comment by vwmaus** [comment]
@ptrkrnstnr can you create a pull request and merge the changes?
